---
- name: Run traceroute commands
  hosts: cisco-devices
  gather_facts: false
  remote_user: cisco
  vars:
    cisco_facts: "{{ lookup('file', 'ip_intf_facts.json') }}"

  vars_prompt:
    

  tasks:
    - include: ./cisco_trace_run.yml
    - include: ./cisco_trace_parse.yml
    - include: ./cisco_trace_record.yml
    #- debug: msg="{{cisco_facts}}"
