---
- name: Run traceroute commands
  hosts: cisco-devices
  gather_facts: false
  remote_user: cisco

  vars_prompt:
    - name: scenario_file
      prompt: "enter scenario filename (.json)"
      default: "scenario-2.json"
      private: no

  vars:
    cisco_facts: "{{ lookup('file', 'ip_intf_facts.json') }}"
    scenario: "{{ lookup('file', './scenarios/' + scenario_file) }}"

  tasks:
    - include: ./cisco_trace_run.yml
    - include: ./cisco_trace_parse.yml
    - include: ./cisco_trace_record.yml
    #- debug: msg="{{cisco_facts}}"
