---
- name: Run traceroute commands
  hosts: cisco-devices
  gather_facts: false
  remote_user: mkashin

  vars_prompt:
    - name: scenario_file
      prompt: "enter scenario filename (.json)"
      default: "scenario-1-baseline.json"
      private: no

  vars:
    cisco_facts: "{{ lookup('file', 'ip_intf_facts.json') }}"
    scenario: "{{ lookup('file', './scenarios/' + scenario_file) }}"

  tasks:
    - name: run traceroute to every other host
      raw: traceroute {{ item.value.0  }}
      when: item.key != inventory_hostname
      with_dict: cisco_facts.1
      register: trace_result

    - name: parse traceroute ouput
      cisco_trace_parse: 
        dest_host="{{ item.item.key }}"
        std_out="{{ item.stdout }}"
      connection: local
      when: item.stdout is defined
      with_items: trace_result.results

    #- name: debug hostvars
    #  debug: var=hostvars[inventory_hostname]

    - name: compare traceroute to scenario and record 
      cisco_trace_compare: 
        dest_host={{ item.key }}
        hostvars="{{ hostvars[inventory_hostname] }}"
        scenario="{{ scenario }}"
        ip_host="{{ cisco_facts.0 }}"
        scenario_file="{{ scenario_file }}"
      when: item.key != inventory_hostname
      with_dict: cisco_facts.1
      connection: local

  tags:
    - run

